# Prometheus Configuration - Production
# Ottimizzato per ambiente Scaleway cloud

global:
  scrape_interval: 30s      # Intervallo più lungo per produzione
  evaluation_interval: 30s  # Valutazione alert ogni 30s
  external_labels:
    environment: 'production'
    region: 'fr-par-1'
    cluster: 'piazzati-prod'

rule_files:
  - "alert-rules.yml"

# Alertmanager configuration (da configurare con Scaleway)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093  # Uncomment when Alertmanager is set up

scrape_configs:
  # FastAPI Backend - Metriche applicazione
  - job_name: 'piazzati-backend-prod'
    static_configs:
      - targets: ['piazzati-backend-prod:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Node Exporter - Metriche sistema host
  - job_name: 'node-exporter-prod'
    static_configs:
      - targets: ['piazzati-node-exporter-prod:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # cAdvisor - Metriche container Docker
  - job_name: 'cadvisor-prod'
    static_configs:
      - targets: ['piazzati-cadvisor-prod:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Exporter - Solo se database self-hosted
  - job_name: 'postgres-exporter-prod'
    static_configs:
      - targets: ['piazzati-postgres-exporter-prod:9187']
    scrape_interval: 30s
    scrape_timeout: 10s
    # Abilitato solo se non si usa Scaleway Managed Database

  # Prometheus self-monitoring
  - job_name: 'prometheus-prod'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Grafana monitoring
  - job_name: 'grafana-prod'
    static_configs:
      - targets: ['piazzati-grafana-prod:3000']
    metrics_path: '/metrics'
    scrape_interval: 60s

  # Nginx monitoring (se abilitato)
  - job_name: 'nginx-prod'
    static_configs:
      - targets: ['piazzati-nginx-prod:9113']
    scrape_interval: 30s
    # Requires nginx-prometheus-exporter sidecar

  # Scaleway Managed Database (se utilizzato)
  # - job_name: 'scaleway-postgres'
  #   static_configs:
  #     - targets: ['postgres-metrics-endpoint:port']
  #   scrape_interval: 60s

# Remote storage per backup metriche (opzionale)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "user"
#       password: "password"

# Remote read per query federate (opzionale)  
# remote_read:
#   - url: "https://your-remote-storage/api/v1/read"
#     basic_auth:
#       username: "user" 
#       password: "password"