name: Safe remote cleanup

on:
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    env:
      SCALEWAY_INSTANCE_IP: ${{ secrets.SCALEWAY_INSTANCE_IP }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SCALEWAY_INSTANCE_IP >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run safe cleanup on remote server
        run: |
          ssh -tt -o ServerAliveInterval=30 -o ServerAliveCountMax=4 -o TCPKeepAlive=yes -i ~/.ssh/id_rsa root@$SCALEWAY_INSTANCE_IP <<'EOF'
            set -euo pipefail
            TS=$(date +%s)
            LOG=/tmp/cleanup-${TS}.log
            echo "Writing cleanup log to $LOG"

            echo "===== BEFORE: df -h =====" | sudo tee -a $LOG
            sudo df -h | sudo tee -a $LOG || true

            echo "\n===== BEFORE: docker system df -v =====" | sudo tee -a $LOG
            sudo docker system df -v 2>/dev/null | sudo tee -a $LOG || echo "docker not available" | sudo tee -a $LOG

            echo "\n===== Running safe cleanup =====" | sudo tee -a $LOG
            echo "apt-get clean" | sudo tee -a $LOG
            sudo apt-get clean 2>&1 | sudo tee -a $LOG || true

            echo "docker container prune -f" | sudo tee -a $LOG
            sudo docker container prune -f 2>&1 | sudo tee -a $LOG || echo "docker container prune failed or docker not available" | sudo tee -a $LOG

            echo "docker image prune -af" | sudo tee -a $LOG
            sudo docker image prune -af 2>&1 | sudo tee -a $LOG || echo "docker image prune failed or docker not available" | sudo tee -a $LOG

            echo "\n===== AFTER: df -h =====" | sudo tee -a $LOG
            sudo df -h | sudo tee -a $LOG || true

            echo "\n===== AFTER: docker system df -v =====" | sudo tee -a $LOG
            sudo docker system df -v 2>/dev/null | sudo tee -a $LOG || echo "docker not available" | sudo tee -a $LOG

            echo "Cleanup log: $LOG"
            echo "---- SUMMARY (head 200) ----"
            sudo head -n 200 $LOG || true
            echo "---- SUMMARY (tail 200) ----"
            sudo tail -n 200 $LOG || true
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
