name: Cleanup now (no remote writes)

on:
  workflow_dispatch: {}

jobs:
  cleanup:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SCALEWAY_INSTANCE_IP >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SCALEWAY_INSTANCE_IP: ${{ secrets.SCALEWAY_INSTANCE_IP }}

      - name: Run safe cleanup (no remote files)
        env:
          SCALEWAY_INSTANCE_IP: ${{ secrets.SCALEWAY_INSTANCE_IP }}
        run: |
          echo "Running safe cleanup on remote host (no remote writes)"
          ssh -o ServerAliveInterval=30 -o ServerAliveCountMax=4 -o TCPKeepAlive=yes -i ~/.ssh/id_rsa root@$SCALEWAY_INSTANCE_IP <<'EOF'
            set -euo pipefail
            echo "===== BEFORE: df -h ====="
            df -h /

            echo "\n===== Running: apt-get clean ====="
            sudo apt-get clean || true

            echo "\n===== Running: docker container prune -f ====="
            sudo docker container prune -f 2>/dev/null || echo "docker not available or prune failed"

            echo "\n===== Running: docker image prune -af ====="
            sudo docker image prune -af 2>/dev/null || echo "docker not available or prune failed"

            echo "\n===== Running: docker volume prune -f ====="
            sudo docker volume prune -f 2>/dev/null || echo "docker not available or prune failed"

            echo "\n===== AFTER: df -h ====="
            df -h /
          EOF
